---
spring:
  config:
    activate:
      on-profile: default
  security:
    mock:
      enabled: true
      users:
        - name: admin@university.edu
          password: pass
        - name: john.smith@university.edu
          password: pass
        - name: jane.doe@university.edu
          password: pass
        - name: alice@student.edu
          password: pass
        - name: bob@student.edu
          password: pass
  sql:
    init:
      platform: h2

cds:
  security:
    mock:
      users:
        - id: admin@university.edu
          password: pass
          roles: [Admin]
        - id: john.smith@university.edu
          password: pass
          roles: [Instructor]
        - id: alice@student.edu
          password: pass
          roles: [Student]
  data-source:
    auto-config:
      enabled: false

# Enable basic auth prompt in browser
server:
  error:
    include-message: always
---
